nome = input("Indique o seu nome\n")
cap_nome = nome.upper()
low_nome = nome.lower()
q_nome = len(nome.replace(" ", ""))
list_nome = nome.split()
q_p_nome = len(list_nome[0])
print(f"Maiúsculas : {cap_nome}")
print(f"Minúsculas : {low_nome}")
print(f"Quantidade sem espaços : {q_nome}")
print(f"Quantidade primeiro nome : {q_p_nome}")
